name: Publish to NuGet

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_FILE: agriffard.csproj
  PACK_OUTPUT: artifacts/package/release

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_FILE }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_FILE }}" --configuration Release --no-restore

      - name: Pack
        run: dotnet pack "${{ env.PROJECT_FILE }}" --configuration Release --no-build --no-restore --output "${{ env.PACK_OUTPUT }}"

      - name: Push to NuGet
        if: ${{ github.event_name == 'release' && github.event.action == 'published' && github.event.release.tag_name != '' }}
        shell: pwsh
        run: |
          Get-ChildItem "${{ env.PACK_OUTPUT }}" -Filter *.nupkg |
          ForEach-Object {
            dotnet nuget push $_.FullName `
              --api-key "${{ secrets.NUGET_API_KEY }}" `
              --source https://api.nuget.org/v3/index.json `
              --skip-duplicate
          }
